### ISSUE TITLE
Porting Effort 

### ISSUE THREAD

**Issue by REGATTE** [osrf/ros2-porting-heuristics#1]
Can someone provide what the metrics stand for 

Porting Effort
`S` & `M`

**Comment by clalancette** [comment]
> Can someone provide what the metrics stand for
> 
> Porting Effort `S` & `M`

I should have documented it in the README.  That is "T-shirt size", which is a shortcut that we use for estimating effort.  That is, we have small, medium, large, and extra-large T-shirt sizes, and that corresponds to the relative amount of work the item would take to port.

If you'd like to submit a PR to the README on this repository to explain that, I'd be happy to review.

**Comment by REGATTE** [comment]
oh okay, 
perfect. Thanks
